spring:
  application:
    name: voting

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    path: /public/swagger

cpf:
  request:
    url: https://gateway.apiserpro.serpro.gov.br/consulta-cpf-df-trial/v1
    token:  Bearer 06aef429-a981-3ec5-a1f8-71d38d86481e